### ISSUE TITLE
Update REST API endpoints for user to apply for a job

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [scrum-gang/jobapplications#25]
(@erickzhao)

This issue falls under epic #1 

The Chrome extension requests the following fields from the user:
 - `company`
     - string, **not null**
     - e.g. `"Matrox inc"`
 - `position`
     - string, **not null**
     - e.g. "FPGA Engineer"`
 - `url`
     - string, **not null**
     - e.g. `"https://www.indeed.ca/viewjob?jk=820a930235f8936f&from"`
 - `status`
    - string, **not null**
    - radio button option with values: `"applied"`, `"to_apply"`
 - `date_posted`:
     - string in HTML5 Date format
     - e.g. `"2017-06-01"`
 - `deadline`:
     - string in HTML5 Date format
     - e.g. `"2017-06-01"`
  - `used_cv`
    - dropdown option with string values being referencing CV ID

| Job Posting Form |
| ------------- |
| ![Job Posting Form](https://i.imgur.com/rQyb5oD.png)  |

---
The form is the same for both internal and external applications. 
There is no distinction from the Extensions perspective.
The response JSON must at minimum contain:
 - a success respone if the job correctly saved
 - a failure response with the reason it wasn't correctly saved

The response JSON can contain any additional information the Frontend team migh need  

---
The generic use case is the following:
 1.  User opens extension on a given job posting website.
 2. The extension scrapes URL from the website and GETs `/postings/<URL-hash>`
 3. If an application already exists for such URL it populates the form with the fields mentioned above 
     If not, the scrapper extract Company, Position and date posted from the website.
     The user fills the remaining fields.
4. Once completed, the extension POSTs the form to `postings/<URL-hash>` if its a new posting
    or PUTs the form to `postings/<URL-hash>` if its an existent posting
---
Ideally then, the Chrome extension only needs 1 endpoints supporting GET/POST/PUT  
Nonetheless, because Frontend has potentially more complicated use cases we can adapt to their requirements.

**Comment by AndreiUngur** [comment]
@CamiloGarciaLaRotta Please let me know if you're satisfied with the API and close this issue if you are :smile:

**Comment by CamiloGarciaLaRotta** [comment]
LGTM thanks!
