### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [scrum-gang/jobapplications#32]
Hey @AndreiUngur !

Here are some issues I encountered using the API:

- There is no official API doc, only the handler function documentation inside the code
  Unfortunately, its outdated (e.g. `/apply/external` now supports status, but the docstring doesn't say that)
- posting a job application should return the job application ID. 
  Currently, we have todo an extra call to `applications/user/<user_id>` and filter the applications by comparing all the fields until we find the one we posted.
  Hoping there are no postings with duplicate fields.
- currently, `/applications/user/<user-id>` returns a 500 error, I have no additional information on why.

None of these action points are urgent on my side, the main use case (submitting job applications) works.
The only action dependent on these issues is to avoid resubmitting a job application that was already added, but its not of major importance.

Cheers!

**Comment by AndreiUngur** [comment]
Thanks for bringing these up, I'll address all of them today :)

**Comment by AndreiUngur** [comment]
1. modified it directly in the repo's wiki, please check it out

2. I'm not sure what you mean, applying returns all the generic information of your application. Here's what I get when I `/apply/external`:

```
[
    {
        "date": "2019-03-21 11:58:47.526299",
        "id": 71,
        "is_inhouse_posting": false,
        "resume": "",
        "status": "Applied",
        "user_id": "potato"
    }
]
```

3. Fixed

**Comment by CamiloGarciaLaRotta** [comment]
Oh in ResonML you have to define a return type, I think when I did it for this request I didn't see `id` beign returned.
Probably that is why I wasn't seeing it and had to query other endpoints to get it.
I'll update my code, thanks!

**Comment by AndreiUngur** [comment]
I guess @CamiloGarciaLaRotta  is satisfied, feel free to re-open this if you aren't!
